[package]
name = "actix-api-error-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[features]
actix = []

[dependencies]
darling = "0.14"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
actix-web = { version = "4.2", optional = true }
convert_case = "0.6"