[package]
name = "resterror"
authors = ["Dimitri Timoz <dimitri.timoz@protonmail.com>, INSAgenda <devs@insagenda.fr>"]
repository = "https://github.com/INSAgenda/resterror"
description = "A simple library to handle REST errors, with a derive macro to generate the error type. It also provides a compatibility layer with actix-web."
version = "0.1.1"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
actix = ["actix-web", "resterror-derive/actix"]
po = ["resterror-derive/po"]

[dependencies]
resterror-derive = { version = "0.1.0", path = "resterror-derive" }
actix-web = { version = "4.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"