[package]
name = "resterror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
actix = []

[dependencies]
resterror-derive = { version = "0.1.0", path = "resterror-derive" }
actix-web = { version = "4.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"